name: twigcn
type: php
docroot: packages/demo/public
php_version: "8.4"
webserver_type: nginx-fpm
database:
  type: mariadb
  version: "10.11"
nodejs_version: "24"
composer_root: packages/demo
omit_containers: [db]

web_extra_exposed_ports:
  - name: vite
    container_port: 5173
    http_port: 5172
    https_port: 5173

hooks:
  post-start:
    - exec: cd packages/demo && composer install --no-interaction
